# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0177c03a63d7a2443fdb94b4a29f7f31066acdc51f5b0bf198e0446fbf2e7a7dd4811677388f99201a4882d723300ca93618ebaa33241339bb70b1ab32205fcf

test:
  secret_key_base: 8d51d0a7ed4e3e845fa576ea908505159b041f8615157bba6888451462d6d1c117f2fb3f5b7b99dedd09af1952c649d365db75ae1fdd9912b1b4bf4142b571e5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
